linear_regression:
  datafile: data/LinearReg/linear_data.csv
  learning_rate: 0.001
  epochs: 10000
  random_seed: 42
  loss_plot_file: plots/LinearReg/linear_loss.png
  model_file: models/LinearReg/linear_model.json
  fit_plot_file: plots/LinearReg/linear_fit.png

logistic_regression:
  datafile: data/LogisticReg/logistic_data.csv
  learning_rate: 0.001
  epochs: 2000
  random_seed: 42
  loss_plot_file: plots/LogisticReg/logistic_loss.png